miniconda_channels:
    - iuc
    - conda-forge
    - bioconda
    - defaults

# HTCondor
condor_host: "galaxy.bioinformatics-atgm.nl"
condor_allow_write: "*.bioinformatics-atgm.nl"
condor_roles:
    - execute
    - central-manager
    - submit
condor_allow_negotiator: '$(ALLOW_WRITE)'
condor_allow_administrator: "$(ALLOW_WRITE)"
condor_network_interface: "{{ ansible_default_ipv4.interface }}"
condor_fs_domain: bioinformatics-atgm.nl
condor_uid_domain: bioinformatics-atgm.nl
condor_trust_uid_domain: 'True'
condor_extra: |
    SLOT_TYPE_1 = cpus=1, ram=4
    NUM_SLOTS_TYPE_1 = 24
    COLLECTOR_NAME = "ATGM Cluster"
    CGROUP_MEMORY_LIMIT_POLICY = soft
