# CVMFS vars
cvmfs_role: client
galaxy_cvmfs_repos_enabled: config-repo
cvmfs_quota_limit: "{{ 1024 * 1024 * 10 }}"

# telegraf
telegraf_agent_package_state: latest
telegraf_agent_output:
  - type: influxdb
    config:
    - urls = ["http://galaxy.bioinformatics-atgm.nl:8086"]
    - database = "telegraf"
telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat
  - plugin: chrony

# Golang
golang_gopath: '/opt/workspace-go'
# Singularity target version
singularity_version: "3.7.0"
singularity_go_path: "{{ golang_install_dir }}"

# Auto upgrades
unattended_origins_patterns:
  - 'origin=Ubuntu,archive=${distro_codename}-security'
  - 'o=Ubuntu,a=${distro_codename}'
  - 'o=Ubuntu,a=${distro_codename}-updates'
  - 'o=Ubuntu,a=${distro_codename}-proposed-updates'

# HTCondor
condor_host: "galaxy.bioinformatics-atgm.nl"
condor_allow_write: "galaxy.bioinformatics-atgm.nl,asgard.bioinformatics-atgm.nl,midgard.bioinformatics-atgm.nl,7kingdoms.bioinformatics-atgm.nl"
condor_allow_negotiator: '$(ALLOW_WRITE)'
condor_allow_administrator: "$(ALLOW_WRITE)"
condor_network_interface: "{{ ansible_default_ipv4.interface }}"
condor_fs_domain: bioinformatics-atgm.nl
condor_uid_domain: bioinformatics-atgm.nl
condor_trust_uid_domain: 'True'
condor_extra: |
    CLAIM_PARTITIONABLE_LEFTOVERS = True
    NUM_SLOTS = 1
    NUM_SLOTS_TYPE_1 = 1
    SLOT_TYPE_1 = cpus=24,ram=100
    SLOT_TYPE_1_PARTITIONABLE = True
    ALLOW_PSLOT_PREEMPTION = False
    STARTD.PROPORTIONAL_SWAP_ASSIGNMENT = True
    COLLECTOR_NAME = "ATGM Cluster"
    CGROUP_MEMORY_LIMIT_POLICY = soft
