---
# Python 3 support
pip_virtualenv_command: /usr/bin/python3 -m virtualenv # usegalaxy_eu.certbot, usegalaxy_eu.tiaas2, galaxyproject.galaxy
certbot_virtualenv_package_name: python3-virtualenv    # usegalaxy_eu.certbot
pip_package: python3-pip                               # geerlingguy.pip


# NGINX
nginx_servers:
  - redirect-ssl
nginx_ssl_servers:
  - cocalc

telegraf_plugins_extra:
  docker:
    plugin: "docker"

openssl_self_sign: false

docker_install_compose: false
docker_users:
  - hexylena
  - telegraf
  - Dirowa
  
#The great code off
tgco_hosts_allowed: Cocalc.atgm.avans.nl
tgco_port: 9091
tgco_debug: True
tgco_path: /srv/the-great-code-off
