---
# Python 3 support
pip_virtualenv_command: /usr/bin/python3 -m virtualenv # usegalaxy_eu.certbot, usegalaxy_eu.tiaas2, galaxyproject.galaxy
certbot_virtualenv_package_name: python3-virtualenv    # usegalaxy_eu.certbot
pip_package: python3-pip                               # geerlingguy.pip


telegraf_agent_hostname: cocalc
telegraf_agent_output:
  - type: file
    config:
    - files = ["stdout", "/tmp/metrics.out"]
    - data_format = "json"
    - json_timestamp_units = "1s"

# NGINX
nginx_selinux_allow_local_connections: true
nginx_servers:
  - redirect-ssl
nginx_servers:
  - cocalc
nginx_enable_default_server: false
nginx_conf_http:
  client_max_body_size: 1g

nginx_ssl_role: self-signed-cert
nginx_conf_ssl_certificate: /etc/ssl/certs/ansible.com.crt
nginx_conf_ssl_certificate_key: /etc/ssl/private/ansible.com.pem
