---
# Python 3 support
pip_virtualenv_command: /usr/bin/python3 -m virtualenv # usegalaxy_eu.certbot, usegalaxy_eu.tiaas2, galaxyproject.galaxy
certbot_virtualenv_package_name: python3-virtualenv    # usegalaxy_eu.certbot
pip_package: python3-pip                               # geerlingguy.pip


# NGINX
nginx_servers:
  - redirect-ssl
nginx_ssl_servers:
  - cocalc

telegraf_plugins_extra:
  docker:
    plugin: "docker"

openssl_self_sign: false

docker_install_compose: false
docker_users:
  - hexylena
  - telegraf
  - Dirowa
