---
# Python 3 support
pip_virtualenv_command: /usr/bin/python3 -m virtualenv # usegalaxy_eu.certbot, usegalaxy_eu.tiaas2, galaxyproject.galaxy
certbot_virtualenv_package_name: python3-virtualenv    # usegalaxy_eu.certbot
pip_package: python3-pip                               # geerlingguy.pip

# PostgreSQL
postgresql_objects_users:
  - name: galaxy-spider
  - name: telegraf
postgresql_objects_databases:
  - name: galaxy-spider
    owner: galaxy-spider
postgresql_objects_privileges:
  - database: galaxy-spider
    roles: telegraf
    privs: SELECT
    objs: ALL_IN_SCHEMA


# PostgreSQL Backups
postgresql_backup_dir: /data/spider-backups
postgresql_backup_local_dir: "{{ '~postgres' | expanduser }}/spider-backups"

# Galaxy
galaxy_create_user: true
galaxy_separate_privileges: true
galaxy_manage_paths: true
galaxy_layout: root-dir
galaxy_root: /srv/spider-galaxy
galaxy_user: {name: galaxy, shell: /bin/bash}
galaxy_commit_id: release_21.09
galaxy_config_style: yaml
galaxy_force_checkout: true

miniconda_prefix: "{{ galaxy_tool_dependency_dir }}/_conda"
miniconda_version: "4.7.12"
miniconda_manage_dependencies: false

galaxy_config:
  galaxy:
    brand: "🧬spider_ATGM🔬"
    admin_users: es.rasche@avans.nl,bk.sanders@avans.nl,m.zhou1@avans.nl,dl.vrins@avans.nl
    database_connection: "postgresql:///galaxy?host=/var/run/postgresql"
    file_path: /data
    check_migrate_tools: false
    tool_data_path: "{{ galaxy_mutable_data_dir }}/tool-data"
    auth_config_file: "{{ galaxy_config_dir }}/auth_conf.xml"
    job_config_file: "{{ galaxy_config_dir }}/job_conf.xml"
    id_secret: "{{ id_secret }}"
    tool_data_table_config_path: /cvmfs/data.galaxyproject.org/byhand/location/tool_data_table_conf.xml,/cvmfs/data.galaxyproject.org/managed/location/tool_data_table_conf.xml
    object_store_store_by: uuid
    #dependency_resolvers_config_file: "{{ galaxy_config_dir }}/dependency_resolvers_conf.xml"
    #containers_resolvers_config_file: "{{ galaxy_config_dir }}/container_resolvers_conf.xml"
    statsd_host: localhost
    statsd_influxdb: true
    # todo: GAT
    trs_servers_config_file: "{{ galaxy_config_dir }}/trs_servers_conf.yml"
    aws_estimate: true
    job_working_directory: /data/spider-jobs
    allow_path_paste: true
    database_engine_option_server_side_cursors: true
    slow_query_log_threshold: 5
    enable_per_request_sql_debugging: true
    watch_tools: 'auto'
    watch_job_rules: 'auto'
    nginx_x_accel_redirect_base: /_x_accel_redirect
    sanitize_all_html: false
    serve_xss_vulnerable_mimetypes: true
    error_email_to: galaxy@galaxy.bioinformatics-atgm.nl
    library_import_dir: /data/library
    show_welcome_with_login: true
    #expose_user_name: true
    enable_quotas: true
    expose_dataset_path: true
    expose_potentially_sensitive_job_metrics: true
    outputs_to_working_directory: true
    cleanup_job: always
    allow_user_deletion: true
    allow_user_impersonation: true
    object_store_config_file: "{{ galaxy_config_dir }}/object_store_conf.xml"
  uwsgi:
    socket: 127.0.0.1:4002
    buffer-size: 16384
    processes: 1
    threads: 4
    offload-threads: 2
    static-map:
      - /static={{ galaxy_server_dir }}/static
      - /favicon.ico={{ galaxy_server_dir }}/static/favicon.ico
    static-safe: client/galaxy/images
    master: true
    virtualenv: "{{ galaxy_venv_dir }}"
    pythonpath: "{{ galaxy_server_dir }}/lib"
    #module: galaxy.webapps.galaxy.buildapp:uwsgi_app()
    mount: /spider=galaxy.webapps.galaxy.buildapp:uwsgi_app()
    manage-script-name: true
    thunder-lock: true
    die-on-term: true
    hook-master-start:
      - unix_signal:2 gracefully_kill_them_all
      - unix_signal:15 gracefully_kill_them_all
    py-call-osafterfork: true
    enable-threads: true
    mule:
      - lib/galaxy/main.py
      - lib/galaxy/main.py
    farm: job-handlers:1,2

galaxy_config_templates:
  - src: templates/galaxy/config/job_conf.xml.j2
    dest: "{{ galaxy_config.galaxy.job_config_file }}"
  #- src: templates/galaxy/config/container_resolvers_conf.xml.j2
    #dest: "{{ galaxy_config.galaxy.containers_resolvers_config_file }}"
  - src: templates/galaxy/config/welcome.html
    dest: "{{ galaxy_config_dir }}/welcome.html"
  - src: templates/galaxy/config/auth_conf.xml
    dest: "{{ galaxy_config.galaxy.auth_config_file }}"
  - src: templates/galaxy/config/object_store_conf.xml
    dest: "{{ galaxy_config.galaxy.object_store_config_file }}"

galaxy_config_files:
#- src: files/galaxy/config/dependency_resolvers_conf.xml
  #dest: "{{ galaxy_config.galaxy.dependency_resolvers_config_file }}"
  #group_vars/sn06.yml
- src: "files/galaxy/config/trs_servers_conf.yml"
  dest: "{{ galaxy_config.galaxy.trs_servers_config_file }}"

# systemd
galaxy_systemd_mode: mule
galaxy_zergpool_listen_addr: 127.0.0.1:8008
galaxy_restart_handler_name: "Restart Galaxy"
galaxy_systemd_unit_name: "spider"
