---
- name: Fetch CSRs
  hosts: all
  become: true
  become_user: root
  tasks:
  - name: Copy file back into tmp
    ansible.builtin.fetch:
      src: "/etc/ssl/private/{{ openssl_domains[0] }}.csr"
      dest: "/tmp/avans-csr-{{ inventory_hostname }}.csr"
      flat: true
    when: nginx_ssl_servers is defined
