- name: Setting up monitoring system
  include_tasks:
    file: setup_cocalc_database.yml
    apply:
      tags: initialise / update backup system monitoring


##########################
# activating the systemD #
##########################

- name: Start Cocalc_backup timer
  ansible.builtin.service:
    name: Cocalc_backup.timer
    state: started