---
- hosts: all
  become: true
  become_user: root
  roles:
    - avans
    #- jnv.unattended-upgrades # Handled by DIF
    - influxdata.chrony
    #- dj-wasabi.telegraf
    #- dev-sec.os-hardening # kinda dangerous
    - Avans_monitoring
  post_tasks:
    - name: Create miniconda enviorment for new users
      include_role:
        name: galaxyproject.miniconda
      vars:
          miniconda_prefix: "{{ project_directory }}/{{ item.year }}/{{ item.name }}/conda"
      become: true
      become_user: "Project{{ item.name }}"
      loop: "{{ atgm_projects }}"
      when: item.host == inventory_hostname