---
- hosts: avans
  become: true
  become_user: root
  roles:
    #- dj-wasabi.telegraf
    - avans
    - jnv.unattended-upgrades # Handled by DIF
    - influxdata.chrony
    #- dj-wasabi.telegraf
    #- dev-sec.os-hardening # kinda dangerous
    - avans_monitoring
    - avans_nginx_user_index
    #- galaxyproject.nginx

