---
- hosts: automation
  become: true
  become_user: root
  vars_files:
    - group_vars/all/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['sshpass']
  roles:
    - geerlingguy.java
    - geerlingguy.jenkins
    - usegalaxy_eu.influxdb
    - cloudalchemy.grafana
