---
- hosts: cocalc
  become: true
  become_user: root
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker-py
  vars_files:
    - group_vars/secret.yml
  pre_tasks:
    - name: Install Dependencies
      package:
        name: ['git', 'cgroup-tools']
  roles:
    - avans
    - galaxyproject.nginx
    - geerlingguy.pip
    - geerlingguy.docker
    - influxdata.chrony
    - dj-wasabi.telegraf
  post_tasks:
    - name: Cocalc
      docker_container:
        name: cocalc
        image: sagemathinc/cocalc
        state: started
        volumes:
        - "{{ cocalc_data_dir }}:/projects"
        env:
            COCALC_NO_IDLE_TIMEOUT: "yes"
        ports:
        - 8443:443
