---
- hosts: cocalc
  become: true
  become_user: root
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker-py
  pre_tasks:
    - name: Fix Hostname
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Install Dependencies
      package:
        name: ['git', 'cgroup-tools']
  roles:
    - avans
    - galaxyproject.nginx
    - geerlingguy.pip
    - geerlingguy.docker
    - galaxyproject.cvmfs
    - influxdata.chrony
    #- dj-wasabi.telegraf
  post_tasks:
    - name: copy Dockerfile
      copy:
        src: ./files/cocalc/
        dest: /opt/cocalc-build/
        owner: root
        group: root
        mode: '0644'
    - name: build container image
      docker_image:
        name: atgm-cocalc:v1
        build:
          path: /opt/cocalc-build/
          source: build
        state: present
    - name: Cocalc
      docker_container:
        name: cocalc
        image: sagemathinc/cocalc
        #image: atgm-cocalc:v1
        state: started
        restart_policy: always
        restart_retries: 3
        volumes:
        - "{{ cocalc_data_dir }}:/projects"
        - "/cvmfs:/cvmfs:shared"
        env:
            COCALC_NO_IDLE_TIMEOUT: "yes"
            R_LIBS_USER: "~/R"
        ports:
        - 8443:443
        - 145.48.6.42:2222:22

    #- name: Run a simple command (argv)
      #community.docker.docker_container_exec:
        #container: foo
        #argv:
          #- /bin/bash
          #- "-c"
          #- "ls -lah > /dev/stderr"
        #chdir: /root
      #register: result

# Delta with base:
# Packages: pandoc-citeproc, cmake
# apt install cmake bamtools bedtools cairo2 git gzip libcairo2 libcairo2-dev libx11-dev locate pip python3-virtuelenv rna-star samtools tree xvfb brew libxt-dev python3-pip build-essential build-essential procps curl file git python3-pip
#
# Cron Scripts: * * * * * /data/cocalc/fix-r-path.sh
# Symlink /usr/bin/jupyter → /usr/local/bin/jupyter
# Rscript -c 'install.packages("Rcmdr")'
# TODO: pip install sqlalchemy for everyone since that seems to require a kernel restart.
