---
- hosts: cocalc
  become: true
  become_user: root
  vars:
    pip_package: python3-pip
    pip_install_packages:
      - name: docker-py
  pre_tasks:
    - name: Fix Hostname
      hostname:
        name: "{{ inventory_hostname }}"
    - name: Install Dependencies
      package:
        name: ['git', 'cgroup-tools']
  roles:
    - avans
    - galaxyproject.nginx
    - geerlingguy.pip
    - geerlingguy.docker
    - galaxyproject.cvmfs
    - influxdata.chrony
    - dj-wasabi.telegraf
  post_tasks:
    - name: Cocalc
      docker_container:
        name: cocalc
        image: sagemathinc/cocalc
        state: started
        restart_policy: always
        restart_retries: 3
        volumes:
        - "{{ cocalc_data_dir }}:/projects"
        - "/cvmfs:/cvmfs:shared"
        env:
            COCALC_NO_IDLE_TIMEOUT: "yes"
            R_LIBS_USER: "~/R"
        ports:
        - 8443:443

# Delta with base:
# Packages: pandoc-citeproc
# Cron Scripts: * * * * * /data/cocalc/fix-r-path.sh
# Symlink /usr/bin/jupyter → /usr/local/bin/jupyter
# Rscript -c 'install.packages("Rcmdr")'
# TODO: pip install sqlalchemy for everyone since that seems to require a kernel restart.
