---
- name: Servers
  hosts: all
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  roles:
    - avans
    #- jnv.unattended-upgrades # Handled by DIF
    - influxdata.chrony
    #- dj-wasabi.telegraf
    #- dev-sec.os-hardening
