---
- name: Servers
  hosts: all
  become: true
  become_user: root
  vars_files:
    - group_vars/secret.yml
  roles:
    - usegalaxy-eu.dynmotd
    - hxr.admin-tools
    - influxdata.chrony
    - dj-wasabi.telegraf
    - dev-sec.os-hardening
  post_tasks:
    # Packages
    - name: Update the apt cache
      apt:
        update_cache: yes
        cache_valid_time: 3600

    - name: Packages we want installed
      apt:
        name:
          - at
          - atop
          - curl
          - htop
          - iftop
          - iotop
          - jq
          - lsof
          - patch
          - strace
          - telnet
          - tmux
          - vim
          - wget
        state: latest

    - name: Ensure services are enabled + started
      systemd:
        name: "{{ item }}"
        enabled: yes
        #state: started
      with_items:
        - atop
        - atd

    # Setup User(s)
    - user:
        name: hexylena
        comment: Helena Rasche
        shell: /bin/bash
        groups: sudo, adm, systemd-journal
        append: yes
    - name: Set authorized key taken from file
      ansible.posix.authorized_key:
        user: hexylena
        state: present
        key: "{{ lookup('file', 'hexylena.pub') }}"
