#- src: galaxyproject.galaxy
  #version: 0.9.17
- src: https://github.com/Slugger70/ansible-galaxy/
  version: 939532e5d925c720a8eae70b07ca58982feb2479
  name: galaxyproject.galaxy
- src: galaxyproject.nginx
  version: 0.7.0
- src: galaxyproject.postgresql
  version: 1.1.0
- src: galaxyproject.postgresql_objects
  version: 1.2.0
- src: geerlingguy.pip
  version: 2.1.0
- src: uchida.miniconda
  version: 0.3.0
- src: https://github.com/Avans-ATGM/ansible-galaxy-systemd
  version: 766d38fe69c71e19378840ff72d314ca4728840a
  name: galaxyproject.galaxy_systemd
- src: usegalaxy_eu.certbot
  version: 0.1.5
- src: cyverse-ansible.singularity
  version: 048c4f178077d05c1e67ae8d9893809aac9ab3b7
- src: gantsign.golang
  version: 2.6.3
- src: galaxyproject.repos
  version: 0.0.2
- src: usegalaxy_eu.rabbitmq
  version: 0.1.0
- src: galaxyproject.cvmfs
  version: 0.2.14
- src: galaxyproject.pulsar
  version: 1.0.9
- src: geerlingguy.java
  version: 1.10.0
- src: geerlingguy.jenkins
  version: 4.3.0
- src: dj-wasabi.telegraf
  version: 0.13.1
- src: influxdata.chrony
  version: master
- src: dev-sec.os-hardening
  version: 6.2.0
- src: cyverse-ansible.singularity
  version: 048c4f178077d05c1e67ae8d9893809aac9ab3b7
- src: gantsign.golang
  version: 2.6.3
- src: https://github.com/Avans-ATGM/ansible-htcondor
  version: 4fca8d776e49edc88537d5a949cfa0f5a519caaf
  name: htcondor-github
- src: usegalaxy_eu.influxdb
  version: v6.0.8
- src: cloudalchemy.grafana
  version: 0.14.2
- src: galaxyproject.gxadmin
  version: 0.0.3
- src: geerlingguy.docker
  version: 3.0.0
- src: galaxyproject.miniconda
  version: 0.1.0
- src: jnv.unattended-upgrades
  version: v1.10.0
- src: geerlingguy.nfs
  version: 2.0.0
- src: galaxyproject.tiaas2
  version: 2.1.3
- src: galaxyproject.self_signed_certs
  version: 0.0.3
- src: usegalaxy_eu.gie_proxy
  version: 0.0.2
- src: galaxyproject.proftpd
  version: 0.3.1
- src: usegalaxy_eu.galaxy_subdomains
  version: 0.0.11
- src: https://github.com/Dirowa/the-great-code-off-server_ansible
  version: c5c6a4a54783affa78075cf89b161d9fc3a67326
  name: the-great-code-off-server
