#general
- name: Create script directory if it doesn't exists
  ansible.builtin.file:
    path: "/etc/telegraf/scripts/"
    state: directory
    mode: '0755'
    owner: "telegraf"

- name: Create a .ssh directory if it doesn't exists
  ansible.builtin.file:
    path: "/etc/telegraf/.ssh/"
    state: directory
    mode: '0755'
    owner: "telegraf"
    group: "telegraf"

- name: create known_hosts file it it doesnt exists
  copy:
    content: ""
    dest: "/etc/telegraf/.ssh/known_hosts"
    force: no
    group: sys
    owner: telegraf
    mode: '0755'

#adding other modules

#monitoring backups
- name: Include monitoring backups
  include_tasks:
    file: monitor_backup.yml
    apply:
      tags: initialise / update backup system monitoring
  tags:
    - when there are student projects

#monitoring backups
- name: Include monitoring student projects
  include_tasks:
    file: monitor_student_projects.yml
    apply:
      tags: initialise / update backup system monitoring

#monitoring backups
- name: Include monitoring Directories
  include_tasks:
    file: monitor_directories.yml
    apply:
      tags: initialise / update backup system monitoring

#monitoring backups
- name: Include monitoring ssh directorie
  include_tasks:
    file: monitor_ssh_directory.yml
    apply:
      tags: initialise / update backup system monitoring


- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: "/etc/telegraf/.ssh/"
    owner: telegraf
    group: telegraf
    mode: '0755'

# reload telegraf, influx, grafana

- name: Restart service telegraf
  ansible.builtin.systemd:
    state: restarted
    daemon_reload: yes
    name: telegraf.service

- name: Make sure a service telegrafruns
  ansible.builtin.systemd:
    state: started
    name: telegraf.service


