- name: Copy main config file of monitoring directories of interest
  template:
    src: monitor_directories.conf.j2
    dest: "/etc/telegraf/telegraf.d/monitor_directories.conf"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'

- name: copy main script file of monitoring directories of interest
  template:
    src: monitor_directories.sh.j2
    dest: "//etc/telegraf/scripts/monitor_directories.sh"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'