# monitoring ssh directory
- name: Copy main config file of monitoring ssh directory
  template:
    src: archive_diskspace.conf.j2
    dest: "/etc/telegraf/telegraf.d/archive_diskspace.conf"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'
  loop: "{{ monitor_ssh_directory }}"
  when: item.working_host == inventory_hostname

- name: copy main script file of monitoring ssh directory
  template:
    src: Archive_diskspace_script.sh.j2
    dest: "/etc/telegraf/scripts/Archive_diskspace_script.sh"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'
  loop: "{{ monitor_ssh_directory }}"
  when: item.working_host == inventory_hostname

- name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /etc/telegraf/.ssh
    owner: jenkins
    group: jenkins
    mode: '0700'


- name: Change ownership SSH key & copy
  ansible.builtin.copy:
    src: "//var/lib/jenkins/workspace/all_servers/roles/Avans_monitoring/files/secret_SSH_key_archive"
    dest: "/etc/telegraf/.ssh/{{ item.encrypted_ssh_private_key }}"
    owner: "telegraf"
    group: "telegraf"
    mode: '0700'
    force: no
  loop: "{{ monitor_ssh_directory }}"
  when: item.working_host == inventory_hostname

  - name: Change file ownership, group and permissions
  ansible.builtin.file:
    path: /etc/telegraf/.ssh
    owner: telegraf
    group: telegraf
    mode: '0755'