#ssh connections


- name: Copy main config file of checking ssh
  template:
    src: ssh_connectivity.conf.j2
    dest: "/etc/telegraf/telegraf.d/ssh_connectivity.conf"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'

- name: copy main script file of checking ssh
  template:
    src: ssh_connectivity.sh.j2
    dest: "//etc/telegraf/scripts/ssh_connectivity.sh"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'