# CVMFS vars
cvmfs_role: client
galaxy_cvmfs_repos_enabled: true
# This is measured in MB: so this should be 10 GB
cvmfs_quota_limit: "{{ 1024 * 10 }}"

# Galaxy vars that will be reused by Pulsar
galaxy_job_metrics_plugins:
  - type: core
  #- type: cpuinfo
  #- type: meminfo
  #- type: uname
  #- type: env
  - type: cgroup
  - type: hostname

# telegraf
telegraf_agent_hostname: "{{ inventory_hostname }}"
telegraf_agent_package_state: latest

# Configure the output to point to an InfluxDB
# running on localhost, and # place data in the
# database "telegraf" which will be created if need be.
telegraf_agent_output:
  - type: influxdb
    config:
    - urls = ["http://galaxy.atgm.avans.nl:8086"]
    - database = "telegraf"

# The default plugins, applied to any telegraf-configured host
telegraf_plugins_default:
  - plugin: cpu
    config:
      - percpu = true
  - plugin: disk
    config:
      - ignore_fs = ["tmpfs", "devtmpfs", "devfs", "iso9660", "overlay", "aufs", "squashfs"]
  - plugin: kernel
  - plugin: processes
  - plugin: io
  - plugin: mem
  - plugin: system
  - plugin: swap
  - plugin: net
  - plugin: netstat
  - plugin: chrony

# Golang
golang_gopath: '/opt/workspace-go'
# Singularity target version
singularity_version: "3.7.0"
singularity_go_path: "{{ golang_install_dir }}"

# Auto upgrades
unattended_origins_patterns:
  - 'origin=Ubuntu,archive=${distro_codename}-security'
  - 'o=Ubuntu,a=${distro_codename}'
  - 'o=Ubuntu,a=${distro_codename}-updates'
  - 'o=Ubuntu,a=${distro_codename}-proposed-updates'
unattended_only_on_ac_power: true

# HTCondor
condor_host: "galaxy.atgm.avans.nl"
condor_allow_write: "galaxy.atgm.avans.nl,test-galaxy.atgm.avans.nl,cocalc.atgm.avans.nl"
condor_allow_negotiator: '$(ALLOW_WRITE)'
condor_allow_administrator: "$(ALLOW_WRITE)"
condor_network_interface: "{{ ansible_default_ipv4.interface }}"
condor_fs_domain: atgm.avans.nl
condor_uid_domain: atgm.avans.nl
condor_trust_uid_domain: 'True'
condor_extra: |
    CLAIM_PARTITIONABLE_LEFTOVERS = True
    NUM_SLOTS = 1
    NUM_SLOTS_TYPE_1 = 1
    SLOT_TYPE_1 = cpus=95%,ram=95%
    SLOT_TYPE_1_PARTITIONABLE = True
    ALLOW_PSLOT_PREEMPTION = False
    STARTD.PROPORTIONAL_SWAP_ASSIGNMENT = True
    COLLECTOR_NAME = "ATGM Cluster"
    CGROUP_MEMORY_LIMIT_POLICY = soft


# NGINX
nginx_selinux_allow_local_connections: true
nginx_enable_default_server: false
nginx_conf_http:
  client_max_body_size: 1g
nginx_servers:
  - homedirs
-nginx_ssl_servers: []

openssl_domains:
- "{{ hostname | default(inventory_hostname) }}"
openssl_email_address: "es.rasche@avans.nl"
openssl_country_name: "NL"
openssl_locality_name: "Tilburg"
openssl_organization_name: "Avans hogeschool"
openssl_organizational_unit_name: "ATGM"
openssl_state_or_province_name: "Noord-Brabant"
certbot_well_known_root: /srv/nginx/_well-known_root
nginx_ssl_role: galaxyproject.self_signed_certs
nginx_conf_ssl_certificate: "/etc/ssl/certs/{{ openssl_domains[0] }}.crt"
nginx_conf_ssl_certificate_key: "/etc/ssl/private/{{ openssl_domains[0] }}.pem"


# Groups & Users
atgm_groups:
- name: students
- name: atgm-user
- name: teacher
- name: sequencing
- name: researcher

#admins
atgm_admins:
- name: hexylena
  groups: sudo,atgm-user, teacher, students,researcher
  users_name: Helena
- name: Bazante
  groups: sudo,atgm-user, teacher, students,researcher
  users_name: Bazante
- name: Dirowa
  groups: sudo,atgm-user, teacher, students,researcher
  users_name: Donny
- name: Miaomiao
  groups: sudo,atgm-user, teacher, students,researcher
  users_name: Miaomiao 

#Researcher
researchers:
- name: Laura
  groups: atgm-user. students,researcher
  users_name: Laura Smolders
  host: asgard.bioinformatics-atgm.nl
 

# Project Accounts
atgm_projects:
# interns
    - name: Mirthe
      year: "2022"
      host: asgard.bioinformatics-atgm.nl
      groups: students,atgm-user
      users_name: "Mirthe Raats 2022,Miaomiao"
    - name: Rubiela
      year: "2022"
      host: asgard.bioinformatics-atgm.nl
      groups: students,atgm-user
      users_name: "Rubiela Rosalia 2022, Miaomiao"
    - name: Gijs
      year: "2022"
      host: asgard.bioinformatics-atgm.nl
      groups: students,atgm-user
      users_name: "Gijs Van den Berg 2022,Nishant"
    - name: Okan
      year: "2022"
      host: asgard.bioinformatics-atgm.nl
      groups: students
      users_name: "Okan Fakoglu 2022, eefje"

  #  #- name: Laura
  #  #  year: "2021"
  #  #  host: asgard.bioinformatics-atgm.nl
  #  - name: Tim
  #    year: "2022"
  #    host: asgard.bioinformatics-atgm.nl
  #    groups: students
# students on midgard

  #  - name: 2022MBI_01
  #    year: "2022"
  #    host: midgard.bioinformatics-atgm.nl
  #    users_name: "Kees and Ted"
  #    groups: Students

# students on isengard
  #  - name: 2022MBI_06
  #    year: "2022"
  #    host: isengard.bioinformatics-atgm.nl
  #    groups: students
  #    users_name: "Charlie and Bob"



#telegraf_archive
monitor_ssh_directory:
 -  ssh_user: dlvrins1
    ssh_ip: archive.surfsara.nl
    directory: //home/gringott/*
    encrypted_ssh_private_key: secret_SSH_key_archive
    working_host: galaxy.atgm.avans.nl
    #jenkins_workspace: /var/lib/jenkins/workspace/all #could probably be deleted

#borg backing up non student projects
#backing user
backup_user: Borg_backup
encrypted_ssh_private_key_archive: secret_archive_ssh_key
backups_to_keep: 3
max_size_local: 1000 # in gb

#backup system with non student prjects (backup locally and on surfsara archive)
#also used as archiving
backup_archive_addres_1: archive.surfsara.nl
backup_archive_usr_1: dlvrins1
back_up_archive_path_1: //home/gringott/backup
max_size_archive: 10000 #in gb

#archiving
host_tree_server: isengard.bioinformatics-atgm.nl
host_user: Dirowa
mirror_key: secret_archive_mirror_key
archive_key: secret_archive_ssh_key
tree_location_on_host: //mnt/teacherfiles/Archive
archiving_home_path: //home/gringott

#backup projects
projects:
  - path: //mnt/studentfiles/student_final_assignment_data
    host: isengard.bioinformatics-atgm.nl
    name_project: final_assignment_data

# Chrony
chrony_server: null
chrony_pool: "pool.ntp.org iburst maxsources 3"

#TMP Reaper
TMP_directories:
- path: "/srv/galaxy/var/tmp"
  host: "galaxy.atgm.avans.nl"
  time: "2d"
