
- name: systemd daemon reload
  systemd:
    daemon_reload: yes
  listen: "SystemD daemon reload"

- name: start galaxy_database_backup.timer
  service:
     name: galaxy_database_backup.timer
     state: started
  listen: "start the galaxy database backup"

- name: restart galaxy_database_backup.timer
  service:
     name: galaxy_database_backup.timer
     state: restarted
  listen: "restart galaxy_database_backup.timer"