
backup_host: galaxy.atgm.avans.nl
backup_location: /data/cocalc_backup
backup_max_size: 1000


directories_to_monitor_size:
- path: /data/cocalc
  max_size: 8904
- path: /data/Teacher_files
  max_size: 8904
- path: /data
  max_size: 8904


ssh_connectivity:
- server: galaxy.atgm.avans.nl

teacher_directory: /data/Teachers_Files

homedirs_port: 8001