#monitoring backups
- name: Setting up monitoring system
  include_tasks:
    file: monitor_backup_galactic_database.yml
    apply:
      tags: initialise / update backup system monitoring

- name: Setting up backup system
  include_tasks:
    file: setup_galactic_backup.yml
    apply:
      tags: initialise / update backup system monitoring