#monitoring backups
- name: Include settingup backup system
  include_tasks:
    file: monitor_student_projects.yml
    apply:
      tags: initialise / update backup system monitoring

- name: Include monitoring backup
  include_tasks:
    file: setup_galactic_backup.yml
    apply:
      tags: initialise / update backup system monitoring