- name: Copy main config file of monitoring backups
  ansible.builtin.copy:
    src: telegraf_conf/monitor_galactic_backup.conf
    dest: "/etc/telegraf/telegraf.d/monitor_galactic_backup.conf"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'

- name: copy main script file of monitoring backups
  template:
    src: monitoring_telegraf/monitor_galactic_backup.sh.j2
    dest: "//etc/telegraf/scripts/monitor_galaxy_backup.sh"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'