
- name: Getting backup_timer ready
  template:
    src: student_project_backup.timer.j2
    dest: "/etc/systemd/system/student_project_backup.timer"
    owner: "root"
    group: "root"
    mode: '0644'

- name: Getting backup borg script ready
  template:
    src: student_project_backup.sh.j2
    dest: "/usr/bin/student_project_backup.sh"
    owner: "root"
    group: "root"
    mode: '0644'

- name: Getting backup borg initialising script ready
  template:
    src: student_project_init_backup.sh.j2
    dest: "/usr/bin/student_project_init_backup.sh"
    owner: "root"
    group: "root"
    mode: '0644'


- name: Getting backup service ready
  template:
    src: student_project_backup.service.j2
    dest: "/etc/systemd/system/student_project_backup.service"
    owner: "root"
    group: "root"
    mode: '0644'

#############################
# create Borg_user accounts #
#############################
- name: Create our backup user
  user:
    name: "{{ backup_user }}"
    home: "/home/{{ backup_user }}"
    shell: "/bin/bash"
    groups: "sudo,atgm-user,root"
    update_password: on_create
    password: "{{ Borg_user_pass | password_hash('sha512') }}"
    append: yes
    generate_ssh_key: yes
    ssh_key_file: "/home/{{ backup_user }}/.ssh/id_rsa"

