

############# General updating ########
- name: Update the apt cache
  apt:
    update_cache: yes
    cache_valid_time: 3600
  ignore_errors: yes

- name: Install basic packages we want everywhere
  package:
    name:
      - acl
      - at
      - atop
      - bc
      - build-essential
      - byobu
      - curl
      - emacs-nox
      - git
      - htop
      - iftop
      - iotop
      - jq
      - lsof
      - make
      - moreutils
      - nano
      - patch
      - screen
      - strace
      - sudo
      - telnet
      - tmux
      - tree
      - vim-nox
      - virtualenv
      - wget
      - zlib1g-dev
      - sshfs
      - fusermount
      - borgbackup
      - tmpreaper
      - mlocate
      - nmap

- name: Ensure services are enabled + started
  systemd:
    name: "{{ item }}"
    enabled: yes
    #state: started
  with_items:
    - atop
    - atd


#add bacup.yml tasks
- name: setting up admin & users accounts / workspaces
  include_tasks:
    file: users.yml
    apply:
      tags: setting up admin & users accounts / workspaces
  tags:
    - when we have users

#add bacup.yml tasks
- name: Include  project backup tasks
  include_tasks:
    file: backup.yml
    apply:
      tags: initialise / update backup system
  tags:
    - when there are projects

- name: adding TMPReaper
  include_tasks:
    file: TMP_reaper.yml
    apply:
      tags: getting tmp_reaper ready
