- name: Getting TMP_reaper script ready
  template:
    src: TMP_reaper.sh.j2
    dest: "/usr/bin/student_project_init_backup.sh"
    owner: "root"
    group: "root"
    mode: '0644'

- name: Create TMP_reaper cron job under /etc/crond
  ansible.builtin.cron:
    name: tmpReaper
    hour: "23"
    user: root
    job: "/usr/bin/student_project_init_backup.sh"

