#########################################################
# General creation of user accounts and user directories#
#########################################################
- name: Create our groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ atgm_groups }}"

- name: Create our admin users
  user:
    name: "{{ item.name }}"
    home: "/home/{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    comment: "{{ item.users_name }}"
    groups: "{{ item.groups | default(omit) }}"
    update_password: on_create
    password: "{{ avans_default_password | password_hash('sha512') }}"
    append: yes
  loop: "{{ atgm_admins }}"

- name: Create our projects
  user:
    name: "{{ item.name }}"
    home: "{{ project_directory }}/{{ item.year }}/{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default(omit) }}"
    update_password: on_create
    password: "{{ avans_default_password | password_hash('sha512') }}"
    append: yes
    comment: "{{ item.users_name }}"

  loop: "{{ atgm_projects }}"
  when: item.host == inventory_hostname

- name: Create data storage to bebacked up with every project
  ansible.builtin.file:
    path: "{{ project_directory }}/{{ item.year }}/{{ item.name }}/data_storage"
    state: directory
    mode: '0755'
    owner: "{{ item.name }}"
  loop: "{{ atgm_projects }}"
  when: item.host == inventory_hostname

#- name: Create miniconda enviorment for new users
#  include_role:
#    name: galaxyproject.miniconda
#  vars:
#    miniconda_prefix: "{{ project_directory }}/{{ item.year }}/{{ item.name }}/conda"
#  loop: "{{ atgm_projects }}"
#  when: item.host == inventory_hostname


- name: create standard readme file
  copy:
    dest: "{{ project_directory }}/{{ item.year }}/{{ item.name }}/Readme"
    force: no
    group: sys
    owner: "{{ item.name }}"
    mode: '0755'
    content: |
      Dear students, welcome to your project directory.
      Use it as you see fit but here are a few things you should know:
      - Put in the data_storage are files which are essentional to yourbackup.
        May something go terrible wrong and all your data is deleted we can retrieve a backup.
        We will make an automated backup weekly (saturday) to an other machine of all files in the data_storage directory
        please keep in mind the size of this directory since due to backup it will be saved 3 times and we dont want to overload the system.

      - We will monitor how much storage space you are using. Try not to go over the 200 GB if it is not nessacery.

      - Therby we have alot of cores to use on this machine (28), however we have to share with other users.
        So try not to use more than 6 cpu at the same time. For big jobs can you always ask Donny and or Bazante what the possibilities are.

      Further try also to make your own Read me files or add to this file with your favourite text editor.
      For example explain what is in every directory and what the input, output are of your scripts / commands so we can recreate everything if needed from the backups

      And remember have fun, if you have any questions please contact Donny or Bazante.
      Small tip to do.

      Change your password from the complicated autogenerated to something you like:
      ```$ passwd {{ item.name }} ``` and then follow instructions on terminal

  loop: "{{ atgm_projects }}"
  when: item.host == inventory_hostname

#- name: Select sensible default for students
#  community.general.alternatives:
#    name: editor
#    path: /bin/nano


####################################
# admins things #
########################


- name: Create a .ssh directory if it doesn't exists
  ansible.builtin.file:
    path: "/home/{{ item.name  }}/.ssh/"
    state: directory
    mode: '0755'
    owner: "{{ item.name }}"
    group: "{{ item.name  }}"
  loop: "{{ atgm_admins }}"

- name: create known_hosts file it it doesnt exists
  copy:
    content: ""
    dest: "/home/{{ item.name  }}/.ssh/known_hosts"
    force: no
    group: sys
    owner: "{{ item.name  }}"
    mode: '0755'
  loop: "{{ atgm_admins }}"

- name: Change ownership SSH key & copy
  ansible.builtin.copy:
    src: "/{{ role_path }}/files/{{ encrypted_ssh_private_key_archive }}"
    dest: "/home/{{ item.name  }}/.ssh/{{ encrypted_ssh_private_key_archive }}"
    owner: "{{ item.name  }}"
    group: "{{ item.name  }}"
    mode: '0700'
    force: no
  loop: "{{ atgm_admins }}"

- name: Change ownership SSH key & copy
  ansible.builtin.copy:
    src: "/{{ role_path }}/files/{{ secret_archive_mirror_key }}"
    dest: "/home/{{ item.name  }}/.ssh/{{ secret_archive_mirror_key }}"
    owner: "{{ item.name  }}"
    group: "{{ item.name  }}"
    mode: '0700'
    force: no
  loop: "{{ atgm_admins }}"
#########################
# getting scripts ready #
#########################

- name: Getting archiving script ready
  template:
    src: bin/scripts/archive_directory.sh.j2
    dest: "/usr/bin/archive_directory.sh"
    owner: "root"
    group: "root"
    mode: '0644'