#########################################################
# General creation of user accounts and user directories#
#########################################################
- name: Create a researcher directory if it doesnt exist yet
  ansible.builtin.file:
    path: "{{ teacher_directory }}/researcher"
    state: directory
    mode: '0755'


- name: Create our groups
  ansible.builtin.group:
    name: "{{ item.name }}"
    state: "{{ item.state | default('present') }}"
  loop: "{{ atgm_groups }}"

##################
#Create accounts #
##################
- name: Create our admin users
  user:
    name: "{{ item.name }}"
    home: "/home/{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    comment: "{{ item.users_name }}"
    groups: "{{ item.groups | default(omit) }}"
    update_password: on_create
    password: "{{ avans_default_password | password_hash('sha512') }}"
    append: yes
  loop: "{{ atgm_admins }}"

- name: Create Software users
  user:
    name: "{{ item.name }}"
    groups: "{{ item.groups | default(omit) }}"
    append: yes
  loop: "{{ atgm_admins }}"

- name: Create our Researchers
  user:
    name: "{{ item.name }}"
    home: "{{ teacher_directory }}/research/{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default(omit) }}"
    update_password: on_create
    password: "{{ avans_default_password | password_hash('sha512') }}"
    append: yes
    comment: "{{ item.users_name }}"
  loop: "{{ researchers }}"
  when: item.host == inventory_hostname


- name: Create our student projects
  user:
    name: "{{ item.name }}"
    home: "{{ project_directory }}/{{ item.year }}/{{ item.name }}"
    shell: "{{ item.shell | default('/bin/bash') }}"
    groups: "{{ item.groups | default(omit) }}"
    update_password: on_create
    password: "{{ avans_default_password | password_hash('sha512') }}"
    append: yes
    comment: "{{ item.users_name }}"
  loop: "{{ atgm_projects }}"
  when: item.host == inventory_hostname

######################
# Create datastorage##
######################

- name: Create data storage to bebacked up with every project
  ansible.builtin.file:
    path: "{{ project_directory }}/{{ item.year }}/{{ item.name }}/data_storage"
    state: directory
    mode: '0755'
    owner: "{{ item.name }}"
  loop: "{{ atgm_projects }}"
  when: item.host == inventory_hostname

- name: Create data storage to bebacked up with every project
  ansible.builtin.file:
    path: "{{ teacher_directory }}/research/{{ item.name }}/data_storage"
    state: directory
    mode: '0755'
    owner: "{{ item.name }}"
  loop: "{{ researchers }}"
  when: item.host == inventory_hostname

#- name: Create miniconda enviorment for new users
#  include_role:
#    name: galaxyproject.miniconda
#  vars:
#    miniconda_prefix: "{{ project_directory }}/{{ item.year }}/{{ item.name }}/conda"
#  loop: "{{ atgm_projects }}"
#  when: item.host == inventory_hostname

######################
#generate readme file#
######################

- name: create standard readme file
  copy:
    dest: "{{ project_directory }}/{{ item.year }}/{{ item.name }}/Readme"
    force: no
    group: sys
    owner: "{{ item.name }}"
    mode: '0755'
    content: |
      Dear students, welcome to your project directory.
      Use it as you see fit but here are a few things you should know:

      - The data_storage directory are for files which are essential to your project.
        May something go terribly wrong and all your data is lost, we can restore it.
        We will make an automated backup weekly (saturday) of all files in the data_storage directory
        Only store the most essential files here, such as your raw data.
        
      - Your account has a maximum allowance of 200Gb. Contact Sander if you need more space.

      - Multiple people are using this machine. Be nice to each other and do not use all the cores/threads on this machine.
        Monitor your resource usage with 'htop'. For intensive tasks, contact Sander to discuss when/how to run this.

      If you have any questions please contact Sander.

      Change your password from the complicated autogenerated to something you like:
      ```$ passwd $USER ``` and then follow instructions on terminal

      there is a directory present in your home. if you put files in there they will become accesible by the webbrowser.
      your personal email is for example {{inventory_hostname}}/~/{item.name}/


  loop: "{{ atgm_projects }}"
  when: item.host == inventory_hostname

#- name: Select sensible default for students
#  community.general.alternatives:
#    name: editor
#    path: /bin/nano


####################################
# admins things #
########################


- name: Create a .ssh directory if it doesn't exists
  ansible.builtin.file:
    path: "/home/{{ item.name  }}/.ssh/"
    state: directory
    mode: '0755'
    owner: "{{ item.name }}"
    group: "{{ item.name  }}"
  loop: "{{ atgm_admins }}"

- name: create known_hosts file it it doesnt exists
  copy:
    content: ""
    dest: "/home/{{ item.name  }}/.ssh/known_hosts"
    force: no
    group: sys
    owner: "{{ item.name  }}"
    mode: '0755'
  loop: "{{ atgm_admins }}"

- name: Change ownership SSH key & copy
  ansible.builtin.copy:
    src: "files/skey/"
    dest: "/home/{{ item.name  }}/.ssh/"
    owner: "{{ item.name  }}"
    group: "{{ item.name  }}"
    mode: '0700'
    force: yes
  loop: "{{ atgm_admins }}"

#########################
# getting scripts ready #
#########################

- name: Getting archiving script ready
  template:
    src: bin/scripts/Archiving/archive_directory.sh.j2
    dest: "/usr/bin/archive_directory.sh"
    owner: "root"
    group: "root"
    mode: '0644'




