project_directory: /mnt/StudentFiles
machine_shortname: Asgard

backup_host: midgard.bioinformatics-atgm.nl
backup_location: /mnt/TeacherFiles/project_backup
backup_max_size: 1000

directories_to_monitor_size:
- path: /mnt/StudentFiles
  max_size: 5632
- path: /mnt/TeacherFiles
  max_size: 5632

#because they are our interns <3
max_student_project_size: 500
