project_directory: /mnt/StudentFiles
teacher_directory: /mnt/TeacherFiles

machine_shortname: Asgard

backup_host: midgard.bioinformatics-atgm.nl
backup_location: "{{ teacher_directory }}/project_backup"
backup_max_size: 1000

directories_to_monitor_size:
- path: "{{ project_directory }}"
  max_size: 5632
- path: "{{ teacher_directory }}"
  max_size: 5632
- path: "/mnt/backup"
  max_size: 1000

#because they are our interns <3
max_student_project_size: 500
max_teacher_project_size: 500

ssh_connectivity:
- server: isengard.bioinformatics-atgm.nl
- server: asgard.bioinformatics-atgm.nl
- server: galaxy.atgm.avans.nl
- server: cocalc.atgm.avans.nl
- server: 7kingdoms.bioinformatics-atgm.nl

#home dirs port to run it on
#80 means no port number is required. otherwise needs to be typed exE ISENGARD.BIOINFORMATICS-atgm.nl:8008/~/username
homedirs_port: 8008