project_directory: /mnt/studentfiles
teacher_directory: /mnt/teacherfiles

machine_shortname: Midgard

backup_host: isengard.bioinformatics-atgm.nl
backup_location: /mnt/backup
backup_max_size: 1000


#monitor certain directories
directories_to_monitor_size:
- path: "{{ project_directory }}"
  max_size: 5632
- path: "{{ teacher_directory }}"
  max_size: 5632
- path: "{{ teacher_directory }}/project_backup"
  max_size: 1000

#max size of student projects
max_student_project_size: 300
max_teacher_project_size: 500

#should be able to ssh too
ssh_connectivity:
- server: asgard.bioinformatics-atgm.nl
- server: galaxy.atgm.avans.nl
- server: cocalc.atgm.avans.nl
- server: asgard.bioinformatics-atgm.nl
- server: 7kingdoms.bioinformatics-atgm.nl

homedirs_port: 80