openssl_domains:
- "galaxy.atgm.avans.nl"
- "*.interactivetoolentrypoint.interactivetool.galaxy.atgm.avans.nl"
- "{{ hostname }}"
openssl_self_sign: false


directories_to_monitor_size:
- path: /data
  max_size: 8904
- path: /data/databases
  max_size: 8904
- path: /data/studentfiles
  max_size: 8904
- path: /data/teacherfiles
  max_size: 8904
- path: /data/files
  max_size: 8904
- path: /data/cocalc_backup
  max_size: 1000

backup_host: none
backup_location: none
