- name: Copy main config file
  template:
    src: archive_diskspace.conf.j2
    dest: "/etc/telegraf/telegraf.d/archive_diskspace.conf"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'
  loop: "{{ monitor_archive }}"
  when: item.host_archive_ansible_encrypted_ssh == inventory_hostname

- name: copy main script file
  template:
    src: archive_diskspace.conf.j2
    dest: "/etc/telegraf/telegraf.d/Archive_diskspace_script.sh"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'
  loop: "{{ monitor_archive }}"
  when: item.host_archive_ansible_encrypted_ssh == inventory_hostname