- name: Copy main config file
  template:
    src: archive_diskspace.conf.j2
    dest: "/etc/telegraf/telegraf.d/archive_diskspace.conf"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'
  loop: "{{ monitor_archive }}"
  when: item.host_archive_ansible_encrypted_ssh == inventory_hostname

- name: copy main script file
  template:
    src: Archive_diskspace_script.sh.j2
    dest: "/etc/telegraf/telegraf.d/Archive_diskspace_script.sh"
    owner: "telegraf"
    group: "telegraf"
    mode: '0644'
  loop: "{{ monitor_archive }}"
  when: item.host_archive_ansible_encrypted_ssh == inventory_hostname

- name: Change ownership SSH key
  ansible.builtin.copy:
    src: /{{ item.jenkins_workspace }}/roles/telegraf_archive/files/{{ item.archive_ansible_encrypted_ssh }}
    dest: "/{{ item.jenkins_workspace }}/roles/telegraf_archive/files/{{ item.archive_ansible_encrypted_ssh }}"
    owner: "telegraf"
    group: "telegraf"
    mode: '0744'
  loop: "{{ monitor_archive }}"
  when: item.host_archive_ansible_encrypted_ssh == inventory_hostname
