- name: Copy main config file
  template:
    src: /roles/telegraf_archive/templates/archive_diskspace.conf.j2
    dest: /etc/telegraf/telegraf.d/archive_diskspace.conf
    owner: telegraf
    group: telegraf
    mode: 0644
  when: "'galaxy.bioinformatics-atgm.nl' in inventory_hostname"

- name: copy main script file
  template:
    src: roles/telegraf_archive/templates/archive_diskspace.conf.j2
    dest: /etc/telegraf/telegraf.d/Archive_diskspace_script.sh
    owner: telegraf
    group: telegraf
    mode: 0644
  when: "'galaxy.bioinformatics-atgm.nl' in inventory_hostname"